languageCode: "ja-JP"
baseUrl: "https://remito.chillout.chat"
title: "/home/remito"
theme: "anubis"
paginate: 10
disqusShortname: "remito"
enableRobotsTXT: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about
    weight: 1
  - identifier: categories
    name: Categories
    title: Categories
    url: /categories
    weight: 2
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags
    weight: 3
  - identifier: rss
    name: RSS
    title: RSS
    url: /index.xml
    weight: 4

params:
  author: "Remito"
  email: remitocat@gmail.com # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
  #   - css/custom.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: true
  disableSummary: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
  - id: twitter
    name: remito
  - id: mastodon
    url: "https://chillout.chat/@remito"
  - id: github
    name: remitocat
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
